require("prototypes.items.Basic-resourses")
require("prototypes.items.item-groups")
require("prototypes.recipe.Basic-resourses-recipe")
require("prototypes.recipe.recipe-category")
require("prototypes.ores.ores")
require("prototypes.autoplace-controls")
require("prototypes.noise-layers")
require("prototypes.fluids.fluids")