
data:extend(
{
  {
    type = "fluid",
    name = "Acrylonitrile",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.417, g=0.310, b=0.416},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Acrylonitrile.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Argon",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.317, g=0.910, b=0.716},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Argon.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "MNT",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.817, g=0.210, b=0.116},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/MNT.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Oleum",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.217, g=0.210, b=0.716},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Oleum.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Seed_oil",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.717, g=0.710, b=0.716},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Seed_oil.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "ADU",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.717, g=0.010, b=0.716},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/ADU.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Air",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.876, g=0.359, b=0.693},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Air.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Ammonia",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.830, g=0.577, b=0.276},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Ammonia.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Anode_slime",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.357, g=0.350, b=0.291},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Anode_slime.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Benzene",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.985, g=0.553, b=0.326},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Benzene.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Bitumi",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.321, g=0.037, b=0.546},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Bitumi.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Butadiene",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.678, g=0.735, b=0.557},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Butadiene.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Carbon_monoxide",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.006, g=0.929, b=0.342},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Carbon_monoxide.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Chlorine",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.733, g=0.609, b=0.777},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Chlorine.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Coal_gas",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.233, g=0.779, b=0.609},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Coal_gas.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Crude_oil",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.229, g=0.117, b=0.193},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Crude_oil.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Dichloroethane",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.487, g=0.588, b=0.262},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Dichloroethane.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Diesel",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.828, g=0.769, b=0.089},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Diesel.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Ethylbenzene",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.789, g=0.808, b=0.723},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Ethylbenzene.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Ethylene",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.838, g=0.698, b=0.613},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Ethylene.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Ferric_chloride_solution",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.606, g=0.849, b=0.233},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Ferric_chloride_solution.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Glycerol",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.627, g=0.698, b=0.123},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Glycerol.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Heavy_oil",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.699, g=0.511, b=0.605},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Heavy_oil.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Hydrochloric_acid",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.924, g=0.455, b=0.690},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Hydrochloric_acid.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Hydrofluoric_acid",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.428, g=0.275, b=0.143},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Hydrofluoric_acid.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Hydrogen",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.246, g=0.228, b=0.405},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Hydrogen.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Hydrogen_chloride",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.590, g=0.929, b=0.488},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Hydrogen_chloride.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Hydrogen_fluoride",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.758, g=0.509, b=0.324},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Hydrogen_fluoride.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Light_oil",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.243, g=0.080, b=0.618},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Light_oil.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Lubricant",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.125, g=0.659, b=0.747},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Lubricant.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Napalm",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.966, g=0.823, b=0.035},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Napalm.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Nitric_acid",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.469, g=0.261, b=0.249},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Nitric_acid.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Nitric_sulfuric_acid_mixture",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.122, g=0.796, b=0.797},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Nitric_sulfuric_acid_mixture.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Nitrogen",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.441, g=0.435, b=0.009},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Nitrogen.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Nitrogen_dioxide",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.508, g=0.158, b=0.310},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Nitrogen_dioxide.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Nitroglycerin",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.545, g=0.825, b=0.820},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Nitroglycerin.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Oxygen",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.205, g=0.830, b=0.116},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Oxygen.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Petroleum_gas",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.679, g=0.726, b=0.755},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Petroleum_gas.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Sodium_tugstate_solution",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.312, g=0.936, b=0.913},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Sodium_tugstate_solution.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Styrene",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.312, g=0.936, b=0.913},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Styrene.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Sulfur_dioxide",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.831, g=0.658, b=0.652},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Sulfur_dioxide.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Sulfuric_acid",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.535, g=0.091, b=0.995},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Sulfuric_acid.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Sulfur_trioxide",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.335, g=0.591, b=0.395},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Sulfur_trioxide.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Uranium_hexafluoride",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.791, g=0.989, b=0.145},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Uranium_hexafluoride.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  
  {
    type = "fluid",
    name = "Uranyl_nitrate",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.293, g=0.104, b=0.802},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Uranyl_nitrate.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Water",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "41.82KJ",
    base_color = {r=0, g=0.34, b=0.6},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Water.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Water_distilled",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "41.82KJ",
    base_color = {r=0, g=0.34, b=0.6},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Water_distilled.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  
  
  {
    type = "fluid",
    name = "Brine",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.680, g=0.245, b=0.985},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Brine.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Germanium_tetrachloride",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.420, g=0.799, b=0.122},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Germanium_tetrachloride.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Stainless_steel_mix_hot",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.688, g=0.749, b=0.890},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Stainless_steel_mix_hot.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Titanium_tetrachloride",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.769, g=0.231, b=0.039},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Titanium_tetrachloride.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Syngas",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.369, g=0.231, b=0.039},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Syngas.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Toluene",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.569, g=0.731, b=0.039},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Toluene.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Trichlorosilane",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.569, g=0.731, b=0.039},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Trichlorosilane.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "Silicon_tetrachloride",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.569, g=0.731, b=0.039},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__NCP-Tech__/graphics/fluid/Silicon_tetrachloride.png",
    order = "a-b-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  
})
