data:extend(
{
  {
    type = "autoplace-control",
    name = "Clay_ore",
    richness = true,
    order = "b-a",
    category = "resource",
  },
  {
    type = "autoplace-control",
    name = "Bauxite_ore",
    richness = true,
    order = "b-a",
    category = "resource",
  },
  {
    type = "autoplace-control",
    name = "Copper_native_ore",
    richness = true,
    order = "b-a",
    category = "resource",
  },
  {
    type = "autoplace-control",
    name = "Scheelite_ore",
    richness = true,
    order = "b-a",
    category = "resource",
  },
  {
    type = "autoplace-control",
    name = "Chalcopyrite_ore",
    richness = true,
    order = "b-a",
    category = "resource",
  },
  {
    type = "autoplace-control",
    name = "Uraninite_ore",
    richness = true,
    order = "b-a",
    category = "resource",
  },
  {
    type = "autoplace-control",
    name = "Quartz_ore",
    richness = true,
    order = "b-a",
    category = "resource",
  },
  {
    type = "autoplace-control",
    name = "Fluorite_ore",
    richness = true,
    order = "b-a",
    category = "resource",
  },
  {
    type = "autoplace-control",
    name = "Cassiterite_ore",
    richness = true,
    order = "b-a",
    category = "resource",
  },
  {
    type = "autoplace-control",
    name = "Galena_ore",
    richness = true,
    order = "b-a",
    category = "resource",
  },
  {
    type = "autoplace-control",
    name = "Rutile_ore",
    richness = true,
    order = "b-a",
    category = "resource",
  },
  {
    type = "autoplace-control",
    name = "Gold_ore",
    richness = true,
    order = "b-a",
    category = "resource",
  },
  {
    type = "autoplace-control",
    name = "Magnetite_ore",
    richness = true,
    order = "b-a",
    category = "resource",
  },
  {
    type = "autoplace-control",
    name = "Brine_pool",
    richness = true,
    order = "b-a",
    category = "resource",
  },
  {
    type = "autoplace-control",
    name = "Graphite_ore",
    richness = true,
    order = "b-a",
    category = "resource",
  },

}
)
