data:extend({

 {
    type= "item",
    name= "Alumina",
    icon = "__NCP-Tech__/graphics/icons/Alumina.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Aluminium_billet",
    icon = "__NCP-Tech__/graphics/icons/Aluminium_billet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Ammonium_Paratungstate",
    icon = "__NCP-Tech__/graphics/icons/Ammonium_Paratungstate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Asphalt_concrete",
    icon = "__NCP-Tech__/graphics/icons/Asphalt_concrete.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Battery",
    icon = "__NCP-Tech__/graphics/icons/Battery.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Battery_casing",
    icon = "__NCP-Tech__/graphics/icons/Battery_casing.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Bauxite_concentrate",
    icon = "__NCP-Tech__/graphics/icons/Bauxite_concentrate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Bauxite_crushed_ore",
    icon = "__NCP-Tech__/graphics/icons/Bauxite_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Bauxite_ore",
    icon = "__NCP-Tech__/graphics/icons/Bauxite_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Bauxite_tailings",
    icon = "__NCP-Tech__/graphics/icons/Bauxite_tailings.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Brass_billet",
    icon = "__NCP-Tech__/graphics/icons/Brass_billet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Brass_plate",
    icon = "__NCP-Tech__/graphics/icons/Brass_plate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Calcium_chloride",
    icon = "__NCP-Tech__/graphics/icons/Calcium_chloride.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Calcium_fluoride",
    icon = "__NCP-Tech__/graphics/icons/Calcium_fluoride.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Calcium_oxide",
    icon = "__NCP-Tech__/graphics/icons/Calcium_oxide.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Calcium_sulfate",
    icon = "__NCP-Tech__/graphics/icons/Calcium_sulfate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Canister",
    icon = "__NCP-Tech__/graphics/icons/Canister.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Carbon_dust",
    icon = "__NCP-Tech__/graphics/icons/Carbon_dust.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Cassiterite_crushed_ore",
    icon = "__NCP-Tech__/graphics/icons/Cassiterite_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Cassiterite_ore",
    icon = "__NCP-Tech__/graphics/icons/Cassiterite_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Chalcopyrite_crushed_ore",
    icon = "__NCP-Tech__/graphics/icons/Chalcopyrite_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Chalcopyrite_ore",
    icon = "__NCP-Tech__/graphics/icons/Chalcopyrite_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Charcoal",
    icon = "__NCP-Tech__/graphics/icons/Charcoal.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Chloroauric_acid",
    icon = "__NCP-Tech__/graphics/icons/Chloroauric_acid.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Chromite_concentrate",
    icon = "__NCP-Tech__/graphics/icons/Chromite_concentrate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Chromite_crushed_ore",
    icon = "__NCP-Tech__/graphics/icons/Chromite_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Chromite_ore",
    icon = "__NCP-Tech__/graphics/icons/Chromite_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Clay_dry",
    icon = "__NCP-Tech__/graphics/icons/Clay_dry.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Clay_wet",
    icon = "__NCP-Tech__/graphics/icons/Clay_wet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Coal_coke",
    icon = "__NCP-Tech__/graphics/icons/Coal_coke.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Coal_tar",
    icon = "__NCP-Tech__/graphics/icons/Coal_tar.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Cobalt_oxide",
    icon = "__NCP-Tech__/graphics/icons/Cobalt_oxide.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Copper_anode",
    icon = "__NCP-Tech__/graphics/icons/Copper_anode.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Copper_billet",
    icon = "__NCP-Tech__/graphics/icons/Copper_billet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Copper_blister",
    icon = "__NCP-Tech__/graphics/icons/Copper_blister.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Copper_consentrate",
    icon = "__NCP-Tech__/graphics/icons/Copper_consentrate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Copper_native",
    icon = "__NCP-Tech__/graphics/icons/Copper_native.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Copper_plate",
    icon = "__NCP-Tech__/graphics/icons/Copper_plate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Copper_rod",
    icon = "__NCP-Tech__/graphics/icons/Copper_rod.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Cordite",
    icon = "__NCP-Tech__/graphics/icons/Cordite.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Cotton",
    icon = "__NCP-Tech__/graphics/icons/Cotton.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Diesel_Fuel",
    icon = "__NCP-Tech__/graphics/icons/Diesel_Fuel.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Direct_reduced_iron",
    icon = "__NCP-Tech__/graphics/icons/Direct_reduced_iron.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Dore_bar",
    icon = "__NCP-Tech__/graphics/icons/Dore_bar.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Ferrochrome",
    icon = "__NCP-Tech__/graphics/icons/Ferrochrome.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Fertilizer",
    icon = "__NCP-Tech__/graphics/icons/Fertilizer.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Fluorite_crushed_ore",
    icon = "__NCP-Tech__/graphics/icons/Fluorite_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Fluorite_ore",
    icon = "__NCP-Tech__/graphics/icons/Fluorite_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Galena_crushed_ore",
    icon = "__NCP-Tech__/graphics/icons/Galena_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Galena_ore",
    icon = "__NCP-Tech__/graphics/icons/Galena_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Glass",
    icon = "__NCP-Tech__/graphics/icons/Glass.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Gold_concentrate",
    icon = "__NCP-Tech__/graphics/icons/Gold_concentrate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Gold_crushed_ore",
    icon = "__NCP-Tech__/graphics/icons/Gold_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Gold_ingot",
    icon = "__NCP-Tech__/graphics/icons/Gold_ingot.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Gold_ore",
    icon = "__NCP-Tech__/graphics/icons/Gold_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Gravel",
    icon = "__NCP-Tech__/graphics/icons/Gravel.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Guncotton",
    icon = "__NCP-Tech__/graphics/icons/Guncotton.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Gunpowder",
    icon = "__NCP-Tech__/graphics/icons/Gunpowder.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lead_billet",
    icon = "__NCP-Tech__/graphics/icons/Lead_billet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lead_bullion",
    icon = "__NCP-Tech__/graphics/icons/Lead_bullion.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lead_concentrate",
    icon = "__NCP-Tech__/graphics/icons/Lead_concentrate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lead_plate",
    icon = "__NCP-Tech__/graphics/icons/Lead_plate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Li-ion_battery",
    icon = "__NCP-Tech__/graphics/icons/Li-ion_battery.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lithium",
    icon = "__NCP-Tech__/graphics/icons/Lithium.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lithium_chloride",
    icon = "__NCP-Tech__/graphics/icons/Lithium_chloride.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lithium_cobalt_oxide",
    icon = "__NCP-Tech__/graphics/icons/Lithium_cobalt_oxide.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lithium_perchlorate",
    icon = "__NCP-Tech__/graphics/icons/Lithium_perchlorate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lithium_tungstate",
    icon = "__NCP-Tech__/graphics/icons/Lithium_tungstate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Magnetite_concentrate",
    icon = "__NCP-Tech__/graphics/icons/Magnetite_concentrate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Magnetite_crushed_ore",
    icon = "__NCP-Tech__/graphics/icons/Magnetite_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Magnetite_ore",
    icon = "__NCP-Tech__/graphics/icons/Magnetite_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Nickel",
    icon = "__NCP-Tech__/graphics/icons/Nickel.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Nickel_cathode",
    icon = "__NCP-Tech__/graphics/icons/Nickel_cathode.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Nickel_concentrate",
    icon = "__NCP-Tech__/graphics/icons/Nickel_concentrate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Nickel_dust",
    icon = "__NCP-Tech__/graphics/icons/Nickel_dust.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Nickel_plate",
    icon = "__NCP-Tech__/graphics/icons/Nickel_plate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Nitre_ore",
    icon = "__NCP-Tech__/graphics/icons/Nitre_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Pentlandite_crushed_ore",
    icon = "__NCP-Tech__/graphics/icons/Pentlandite_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Pentlandite_ore",
    icon = "__NCP-Tech__/graphics/icons/Pentlandite_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Petroleum_jelly",
    icon = "__NCP-Tech__/graphics/icons/Petroleum_jelly.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Pig_iron",
    icon = "__NCP-Tech__/graphics/icons/Pig_iron.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Pig_iron_early",
    icon = "__NCP-Tech__/graphics/icons/Pig_iron.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Plaster",
    icon = "__NCP-Tech__/graphics/icons/Plaster.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Plastic_pellets",
    icon = "__NCP-Tech__/graphics/icons/Plastic_pellets.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Plastics",
    icon = "__NCP-Tech__/graphics/icons/Plastics.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Quarried_stone",
    icon = "__NCP-Tech__/graphics/icons/Quarried_stone.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Quartz",
    icon = "__NCP-Tech__/graphics/icons/Quartz.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Quartz_rock",
    icon = "__NCP-Tech__/graphics/icons/Quartz_rock.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Raw_wood",
    icon = "__NCP-Tech__/graphics/icons/Raw_wood.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Resin",
    icon = "__NCP-Tech__/graphics/icons/Resin.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Rubber",
    icon = "__NCP-Tech__/graphics/icons/Rubber.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Rutile_crushed_ore",
    icon = "__NCP-Tech__/graphics/icons/Rutile_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Rutile_ore",
    icon = "__NCP-Tech__/graphics/icons/Rutile_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Salt",
    icon = "__NCP-Tech__/graphics/icons/Salt.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Saltpeter",
    icon = "__NCP-Tech__/graphics/icons/Saltpeter.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Sand",
    icon = "__NCP-Tech__/graphics/icons/Sand.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Scheelite_crushed_ore",
    icon = "__NCP-Tech__/graphics/icons/Scheelite_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Scheelite_ore",
    icon = "__NCP-Tech__/graphics/icons/Scheelite_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Silicon_boule",
    icon = "__NCP-Tech__/graphics/icons/Silicon_boule.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Silicon_carbide",
    icon = "__NCP-Tech__/graphics/icons/Silicon_carbide.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Silicon_dioxide",
    icon = "__NCP-Tech__/graphics/icons/Silicon_dioxide.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Silicon_wafer",
    icon = "__NCP-Tech__/graphics/icons/Silicon_wafer.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Silt",
    icon = "__NCP-Tech__/graphics/icons/Silt.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Silver_ingot",
    icon = "__NCP-Tech__/graphics/icons/Silver_ingot.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Silver_nitrate",
    icon = "__NCP-Tech__/graphics/icons/Silver_nitrate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Silver_oxide",
    icon = "__NCP-Tech__/graphics/icons/Silver_oxide.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Silver-oxide_battery",
    icon = "__NCP-Tech__/graphics/icons/Silver-oxide_battery.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Slag",
    icon = "__NCP-Tech__/graphics/icons/Slag.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Slag_dust",
    icon = "__NCP-Tech__/graphics/icons/Slag_dust.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Sodium_hydroxide",
    icon = "__NCP-Tech__/graphics/icons/Sodium_hydroxide.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Sphalerite_ore",
    icon = "__NCP-Tech__/graphics/icons/Sphalerite_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Stainless_steel_billet",
    icon = "__NCP-Tech__/graphics/icons/Stainless_steel_billet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Steel_billet",
    icon = "__NCP-Tech__/graphics/icons/Steel_billet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Stone_crushed",
    icon = "__NCP-Tech__/graphics/icons/Stone_crushed.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Styrofoam",
    icon = "__NCP-Tech__/graphics/icons/Styrofoam.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Sulfur",
    icon = "__NCP-Tech__/graphics/icons/Sulfur.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Tin_billet",
    icon = "__NCP-Tech__/graphics/icons/Tin_billet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Tin_concentrate",
    icon = "__NCP-Tech__/graphics/icons/Tin_concentrate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Titanium",
    icon = "__NCP-Tech__/graphics/icons/Titanium.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Titanium_nitride_film",
    icon = "__NCP-Tech__/graphics/icons/Titanium_nitride_film.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Titanium_oxide",
    icon = "__NCP-Tech__/graphics/icons/Titanium_oxide.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Tungsten_carbide",
    icon = "__NCP-Tech__/graphics/icons/Tungsten_carbide.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Tungsten_oxide",
    icon = "__NCP-Tech__/graphics/icons/Tungsten_oxide.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Tungsten_powder",
    icon = "__NCP-Tech__/graphics/icons/Tungsten_powder.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Uraninite_concentrate",
    icon = "__NCP-Tech__/graphics/icons/Uraninite_concentrate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Uraninite_ore",
    icon = "__NCP-Tech__/graphics/icons/Uraninite_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Uranium_235_pellet",
    icon = "__NCP-Tech__/graphics/icons/Uranium_235_pellet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Uranium_235_rod",
    icon = "__NCP-Tech__/graphics/icons/Uranium_235_rod.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Uranium_235_rod_alt",
    icon = "__NCP-Tech__/graphics/icons/Uranium_235_rod_alt.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Uranium_238_pellet",
    icon = "__NCP-Tech__/graphics/icons/Uranium_238_pellet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Uranium_oxide_powder_235",
    icon = "__NCP-Tech__/graphics/icons/Uranium_oxide_powder_235.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Uranium_oxide_powder_238",
    icon = "__NCP-Tech__/graphics/icons/Uranium_oxide_powder_238.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Wood",
    icon = "__NCP-Tech__/graphics/icons/Wood.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Wooden_board",
    icon = "__NCP-Tech__/graphics/icons/Wooden_board.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Wrought_iron_billet",
    icon = "__NCP-Tech__/graphics/icons/Wrought_iron_billet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Yellow_cake",
    icon = "__NCP-Tech__/graphics/icons/Yellow_cake.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Zinc_concentrate",
    icon = "__NCP-Tech__/graphics/icons/Zinc_concentrate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Zinc_matte",
    icon = "__NCP-Tech__/graphics/icons/Zinc_matte.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Zinc_plate",
    icon = "__NCP-Tech__/graphics/icons/Zinc_plate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Zircon",
    icon = "__NCP-Tech__/graphics/icons/Zircon.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Zirconium_dust",
    icon = "__NCP-Tech__/graphics/icons/Zirconium_dust.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Zirconium_ingot",
    icon = "__NCP-Tech__/graphics/icons/Zirconium_ingot.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Zirconium_plate",
    icon = "__NCP-Tech__/graphics/icons/Zirconium_plate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Zirconium_tube",
    icon = "__NCP-Tech__/graphics/icons/Zirconium_tube.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  
  
  
  
  })
