data.raw["item"]["coal"].fuel_value =nil
data.raw["item"]["raw-wood"].fuel_value =nil

data:extend({

 {
    type= "item",
    name= "Alumina",
    icon = "__NCP-Tech__/graphics/icons/Alumina.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Raw_ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Nichrome",
    icon = "__NCP-Tech__/graphics/icons/Nichrome.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Raw_ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lithium_carbonate",
    icon = "__NCP-Tech__/graphics/icons/Lithium_carbonate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Raw_ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Sodium_chlorate",
    icon = "__NCP-Tech__/graphics/icons/Sodium_chlorate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Raw_ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Sodium_perchlorate",
    icon = "__NCP-Tech__/graphics/icons/Sodium_perchlorate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Raw_ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Quarried_limestone",
    icon = "__NCP-Tech__/graphics/icons/Quarried_limestone.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Raw_ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Carbon_fiber_fabric",
    icon = "__NCP-Tech__/graphics/icons/Carbon_fiber_fabric.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Raw_ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Carbon_fiber_filament",
    icon = "__NCP-Tech__/graphics/icons/Carbon_fiber_filament.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Raw_ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "DNT",
    icon = "__NCP-Tech__/graphics/icons/DNT.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Raw_ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "PAN_filament",
    icon = "__NCP-Tech__/graphics/icons/PAN_filament.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Raw_ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "TNT",
    icon = "__NCP-Tech__/graphics/icons/TNT.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Raw_ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Limestone_crushed",
    icon = "__NCP-Tech__/graphics/icons/Limestone_crushed.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Raw_ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Aluminium_billet",
    icon = "__NCP-Tech__/graphics/icons/Aluminium_billet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Ammonium_Paratungstate",
    icon = "__NCP-Tech__/graphics/icons/Ammonium_Paratungstate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Asphalt_concrete",
    icon = "__NCP-Tech__/graphics/icons/Asphalt_concrete.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Battery",
    icon = "__NCP-Tech__/graphics/icons/Battery.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Battery_casing",
    icon = "__NCP-Tech__/graphics/icons/Battery_casing.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Bauxite_concentrate",
    icon = "__NCP-Tech__/graphics/icons/Bauxite_concentrate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Bauxite_crushed_ore",
    icon = "__NCP-Tech__/graphics/icons/Bauxite_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Crushed",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Bauxite_ore",
    icon = "__NCP-Tech__/graphics/icons/Bauxite_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Bauxite_tailings",
    icon = "__NCP-Tech__/graphics/icons/Bauxite_tailings.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Brass_billet",
    icon = "__NCP-Tech__/graphics/icons/Brass_billet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Brass_plate",
    icon = "__NCP-Tech__/graphics/icons/Brass_plate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Calcium_chloride",
    icon = "__NCP-Tech__/graphics/icons/Calcium_chloride.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Calcium_fluoride",
    icon = "__NCP-Tech__/graphics/icons/Calcium_fluoride.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Calcium_oxide",
    icon = "__NCP-Tech__/graphics/icons/Calcium_oxide.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Calcium_sulfate",
    icon = "__NCP-Tech__/graphics/icons/Calcium_sulfate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Canister",
    icon = "__NCP-Tech__/graphics/icons/Canister.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Carbon_dust",
    icon = "__NCP-Tech__/graphics/icons/Carbon_dust.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Cassiterite_crushed_ore",
    icon = "__NCP-Tech__/graphics/icons/Cassiterite_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Crushed",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Cassiterite_ore",
    icon = "__NCP-Tech__/graphics/icons/Cassiterite_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Chalcopyrite_crushed_ore",
    icon = "__NCP-Tech__/graphics/icons/Chalcopyrite_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Crushed",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Chalcopyrite_ore",
    icon = "__NCP-Tech__/graphics/icons/Chalcopyrite_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Charcoal",
    icon = "__NCP-Tech__/graphics/icons/Charcoal.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Chloroauric_acid",
    icon = "__NCP-Tech__/graphics/icons/Chloroauric_acid.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Chromite_concentrate",
    icon = "__NCP-Tech__/graphics/icons/Chromite_concentrate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Chromite_crushed_ore",
    icon = "__NCP-Tech__/graphics/icons/Chromite_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Crushed",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Chromite_ore",
    icon = "__NCP-Tech__/graphics/icons/Chromite_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Clay_dry",
    icon = "__NCP-Tech__/graphics/icons/Clay_dry.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Clay_wet",
    icon = "__NCP-Tech__/graphics/icons/Clay_wet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Coal_coke",
    icon = "__NCP-Tech__/graphics/icons/Coal_coke.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
	fuel_value="280MJ"
  },
  {
    type= "item",
    name= "Coal_tar",
    icon = "__NCP-Tech__/graphics/icons/Coal_tar.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Cobalt_oxide",
    icon = "__NCP-Tech__/graphics/icons/Cobalt_oxide.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Copper_anode",
    icon = "__NCP-Tech__/graphics/icons/Copper_anode.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Copper_billet",
    icon = "__NCP-Tech__/graphics/icons/Copper_billet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Copper_blister",
    icon = "__NCP-Tech__/graphics/icons/Copper_blister.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Copper_concentrate",
    icon = "__NCP-Tech__/graphics/icons/Copper_concentrate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Copper_native_ore",
    icon = "__NCP-Tech__/graphics/icons/Copper_native_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Copper_plate",
    icon = "__NCP-Tech__/graphics/icons/Copper_plate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Copper_rod",
    icon = "__NCP-Tech__/graphics/icons/Copper_rod.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Cordite",
    icon = "__NCP-Tech__/graphics/icons/Cordite.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Cotton",
    icon = "__NCP-Tech__/graphics/icons/Cotton.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Diesel_canister",
    icon = "__NCP-Tech__/graphics/icons/Diesel_canister.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Direct_reduced_iron",
    icon = "__NCP-Tech__/graphics/icons/Direct_reduced_iron.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Dore_bar",
    icon = "__NCP-Tech__/graphics/icons/Dore_bar.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Ferrochrome",
    icon = "__NCP-Tech__/graphics/icons/Ferrochrome.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Fertilizer",
    icon = "__NCP-Tech__/graphics/icons/Fertilizer.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Fluorite_crushed_ore",
    icon = "__NCP-Tech__/graphics/icons/Fluorite_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Crushed",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Fluorite_ore",
    icon = "__NCP-Tech__/graphics/icons/Fluorite_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Galena_crushed_ore",
    icon = "__NCP-Tech__/graphics/icons/Galena_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Crushed",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Galena_ore",
    icon = "__NCP-Tech__/graphics/icons/Galena_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Glass",
    icon = "__NCP-Tech__/graphics/icons/Glass.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Gold_concentrate",
    icon = "__NCP-Tech__/graphics/icons/Gold_concentrate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Gold_crushed_ore",
    icon = "__NCP-Tech__/graphics/icons/Gold_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Crushed",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Gold_ingot",
    icon = "__NCP-Tech__/graphics/icons/Gold_ingot.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Gold_ore",
    icon = "__NCP-Tech__/graphics/icons/Gold_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Gravel",
    icon = "__NCP-Tech__/graphics/icons/Gravel.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Guncotton",
    icon = "__NCP-Tech__/graphics/icons/Guncotton.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Gunpowder",
    icon = "__NCP-Tech__/graphics/icons/Gunpowder.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lead_billet",
    icon = "__NCP-Tech__/graphics/icons/Lead_billet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lead_bullion",
    icon = "__NCP-Tech__/graphics/icons/Lead_bullion.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lead_concentrate",
    icon = "__NCP-Tech__/graphics/icons/Lead_concentrate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lead_plate",
    icon = "__NCP-Tech__/graphics/icons/Lead_plate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Li-ion_battery",
    icon = "__NCP-Tech__/graphics/icons/Li-ion_battery.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lithium",
    icon = "__NCP-Tech__/graphics/icons/Lithium.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lithium_chloride",
    icon = "__NCP-Tech__/graphics/icons/Lithium_chloride.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lithium_cobalt_oxide",
    icon = "__NCP-Tech__/graphics/icons/Lithium_cobalt_oxide.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lithium_perchlorate",
    icon = "__NCP-Tech__/graphics/icons/Lithium_perchlorate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lithium_tungstate",
    icon = "__NCP-Tech__/graphics/icons/Lithium_tungstate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Magnetite_concentrate",
    icon = "__NCP-Tech__/graphics/icons/Magnetite_concentrate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Magnetite_crushed_ore",
    icon = "__NCP-Tech__/graphics/icons/Magnetite_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Crushed",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Magnetite_ore",
    icon = "__NCP-Tech__/graphics/icons/Magnetite_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Nickel",
    icon = "__NCP-Tech__/graphics/icons/Nickel.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Nickel_cathode",
    icon = "__NCP-Tech__/graphics/icons/Nickel_cathode.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Nickel_concentrate",
    icon = "__NCP-Tech__/graphics/icons/Nickel_concentrate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Nickel_dust",
    icon = "__NCP-Tech__/graphics/icons/Nickel_dust.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Nickel_plate",
    icon = "__NCP-Tech__/graphics/icons/Nickel_plate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Pentlandite_crushed_ore",
    icon = "__NCP-Tech__/graphics/icons/Pentlandite_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Crushed",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Pentlandite_ore",
    icon = "__NCP-Tech__/graphics/icons/Pentlandite_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Petroleum_jelly",
    icon = "__NCP-Tech__/graphics/icons/Petroleum_jelly.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Pig_iron",
    icon = "__NCP-Tech__/graphics/icons/Pig_iron.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Pig_iron_early",
    icon = "__NCP-Tech__/graphics/icons/Pig_iron.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Plaster",
    icon = "__NCP-Tech__/graphics/icons/Plaster.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Plastic_pellets",
    icon = "__NCP-Tech__/graphics/icons/Plastic_pellets.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Plastics",
    icon = "__NCP-Tech__/graphics/icons/Plastics.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Quarried_stone",
    icon = "__NCP-Tech__/graphics/icons/Quarried_stone.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Quartz",
    icon = "__NCP-Tech__/graphics/icons/Quartz.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Quartz_rock",
    icon = "__NCP-Tech__/graphics/icons/Quartz_rock.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Quartz_crushed",
    icon = "__NCP-Tech__/graphics/icons/Quartz_crushed.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Crushed",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Quartz_seed",
    icon = "__NCP-Tech__/graphics/icons/Quartz_seed.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Resin",
    icon = "__NCP-Tech__/graphics/icons/Resin.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Rubber",
    icon = "__NCP-Tech__/graphics/icons/Rubber.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Rutile_crushed_ore",
    icon = "__NCP-Tech__/graphics/icons/Rutile_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Crushed",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Rutile_ore",
    icon = "__NCP-Tech__/graphics/icons/Rutile_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Salt",
    icon = "__NCP-Tech__/graphics/icons/Salt.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Potassium_nitrate",
    icon = "__NCP-Tech__/graphics/icons/Potassium_nitrate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Sand",
    icon = "__NCP-Tech__/graphics/icons/Sand.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Scheelite_crushed_ore",
    icon = "__NCP-Tech__/graphics/icons/Scheelite_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Crushed",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Scheelite_ore",
    icon = "__NCP-Tech__/graphics/icons/Scheelite_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Silicon_boule",
    icon = "__NCP-Tech__/graphics/icons/Silicon_boule.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Silicon_carbide",
    icon = "__NCP-Tech__/graphics/icons/Silicon_carbide.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Silicon_dioxide",
    icon = "__NCP-Tech__/graphics/icons/Silicon_dioxide.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Silicon_wafer",
    icon = "__NCP-Tech__/graphics/icons/Silicon_wafer.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Silt",
    icon = "__NCP-Tech__/graphics/icons/Silt.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Silver_ingot",
    icon = "__NCP-Tech__/graphics/icons/Silver_ingot.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Silver_nitrate",
    icon = "__NCP-Tech__/graphics/icons/Silver_nitrate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Silver_oxide",
    icon = "__NCP-Tech__/graphics/icons/Silver_oxide.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Silver-oxide_battery",
    icon = "__NCP-Tech__/graphics/icons/Silver-oxide_battery.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Slag",
    icon = "__NCP-Tech__/graphics/icons/Slag.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Slag_dust",
    icon = "__NCP-Tech__/graphics/icons/Slag_dust.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Sodium_hydroxide",
    icon = "__NCP-Tech__/graphics/icons/Sodium_hydroxide.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Sphalerite_ore",
    icon = "__NCP-Tech__/graphics/icons/Sphalerite_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Stainless_steel_billet",
    icon = "__NCP-Tech__/graphics/icons/Stainless_steel_billet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Steel_billet",
    icon = "__NCP-Tech__/graphics/icons/Steel_billet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Stone_crushed",
    icon = "__NCP-Tech__/graphics/icons/Stone_crushed.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Crushed",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Styrofoam",
    icon = "__NCP-Tech__/graphics/icons/Styrofoam.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Sulfur",
    icon = "__NCP-Tech__/graphics/icons/Sulfur.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Tin_billet",
    icon = "__NCP-Tech__/graphics/icons/Tin_billet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Tin_concentrate",
    icon = "__NCP-Tech__/graphics/icons/Tin_concentrate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Titanium_billet",
    icon = "__NCP-Tech__/graphics/icons/Titanium_billet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Titanium_nitride_film",
    icon = "__NCP-Tech__/graphics/icons/Titanium_nitride_film.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Titanium_dioxide",
    icon = "__NCP-Tech__/graphics/icons/Titanium_dioxide.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Tungsten_carbide_billet",
    icon = "__NCP-Tech__/graphics/icons/Tungsten_carbide_billet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Tungsten_oxide",
    icon = "__NCP-Tech__/graphics/icons/Tungsten_oxide.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Tungsten_powder",
    icon = "__NCP-Tech__/graphics/icons/Tungsten_powder.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Uraninite_ore_concentrate",
    icon = "__NCP-Tech__/graphics/icons/Uraninite_ore_concentrate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Uraninite_ore",
    icon = "__NCP-Tech__/graphics/icons/Uraninite_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Uranium_235_pellet",
    icon = "__NCP-Tech__/graphics/icons/Uranium_235_pellet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Uranium_235_rod",
    icon = "__NCP-Tech__/graphics/icons/Uranium_235_rod.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Uranium_235_rod_alt",
    icon = "__NCP-Tech__/graphics/icons/Uranium_235_rod_alt.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Uranium_238_pellet",
    icon = "__NCP-Tech__/graphics/icons/Uranium_238_pellet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Uranium_oxide_powder_235",
    icon = "__NCP-Tech__/graphics/icons/Uranium_oxide_powder_235.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Uranium_oxide_powder_238",
    icon = "__NCP-Tech__/graphics/icons/Uranium_oxide_powder_238.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Wood",
    icon = "__NCP-Tech__/graphics/icons/Wood.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
	fuel_value="180MJ"
  },
  {
    type= "item",
    name= "Wooden_board",
    icon = "__NCP-Tech__/graphics/icons/Wooden_board.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Wrought_iron_billet",
    icon = "__NCP-Tech__/graphics/icons/Wrought_iron_billet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Iron_billet",
    icon = "__NCP-Tech__/graphics/icons/Wrought_iron_billet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Yellowcake",
    icon = "__NCP-Tech__/graphics/icons/Yellowcake.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Zinc_concentrate",
    icon = "__NCP-Tech__/graphics/icons/Zinc_concentrate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Zinc_matte",
    icon = "__NCP-Tech__/graphics/icons/Zinc_matte.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Zinc_plate",
    icon = "__NCP-Tech__/graphics/icons/Zinc_plate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Zircon",
    icon = "__NCP-Tech__/graphics/icons/Zircon.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Zirconium_dust",
    icon = "__NCP-Tech__/graphics/icons/Zirconium_dust.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Zirconium_billet",
    icon = "__NCP-Tech__/graphics/icons/Zirconium_billet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Zirconium_plate",
    icon = "__NCP-Tech__/graphics/icons/Zirconium_plate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Zirconium_tube",
    icon = "__NCP-Tech__/graphics/icons/Zirconium_tube.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  
  
  ----------------------------
  
  {
    type= "item",
    name= "Lead_solder_ingot",
    icon = "__NCP-Tech__/graphics/icons/Lead_solder_ingot.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lead_solder",
    icon = "__NCP-Tech__/graphics/icons/Lead_solder.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lead_free_solder_ingot",
    icon = "__NCP-Tech__/graphics/icons/Lead_free_solder_ingot.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lead_free_solder",
    icon = "__NCP-Tech__/graphics/icons/Lead_free_solder.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Solder_paste",
    icon = "__NCP-Tech__/graphics/icons/Solder_paste.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Magnesium_hydroxide",
    icon = "__NCP-Tech__/graphics/icons/Magnesium_hydroxide.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Magnesium_oxide",
    icon = "__NCP-Tech__/graphics/icons/Magnesium_oxide.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Ferrosilicon",
    icon = "__NCP-Tech__/graphics/icons/Ferrosilicon.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Magnesium",
    icon = "__NCP-Tech__/graphics/icons/Magnesium.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Graphite_ore",
    icon = "__NCP-Tech__/graphics/icons/Graphite_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Graphite_crushed_ore",
    icon = "__NCP-Tech__/graphics/icons/Graphite_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Graphite_crushed",
    icon = "__NCP-Tech__/graphics/icons/Graphite_crushed.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Graphite_dust",
    icon = "__NCP-Tech__/graphics/icons/Graphite_dust.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Graphite_electrode",
    icon = "__NCP-Tech__/graphics/icons/Graphite_electrode.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Cement",
    icon = "__NCP-Tech__/graphics/icons/Cement.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Graphite_crucible",
    icon = "__NCP-Tech__/graphics/icons/Graphite_crucible.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Graphite_rod",
    icon = "__NCP-Tech__/graphics/icons/Graphite_rod.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Silicon_furnace",
    icon = "__NCP-Tech__/graphics/icons/Silicon_furnace.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Cement_bauxite",
    icon = "__NCP-Tech__/graphics/icons/Cement_bauxite.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Cement_slag",
    icon = "__NCP-Tech__/graphics/icons/Cement_slag.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Calcium_carbonate",
    icon = "__NCP-Tech__/graphics/icons/Calcium_carbonate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Cement_clinker",
    icon = "__NCP-Tech__/graphics/icons/Cement_clinker.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Concrete_block",
    icon = "__NCP-Tech__/graphics/icons/Concrete_block.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Concrete_wall",
    icon = "__NCP-Tech__/graphics/icons/Concrete_wall.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Sodium_carbonate",
    icon = "__NCP-Tech__/graphics/icons/Sodium_carbonate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Diamond_uncut",
    icon = "__NCP-Tech__/graphics/icons/Diamond_uncut.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Aluminosilicate_glass",
    icon = "__NCP-Tech__/graphics/icons/Aluminosilicate_glass.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Fiberglass_roving",
    icon = "__NCP-Tech__/graphics/icons/Fiberglass_roving.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Fiberglass_cloth",
    icon = "__NCP-Tech__/graphics/icons/Fiberglass_cloth.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Fiberglass_laminate",
    icon = "__NCP-Tech__/graphics/icons/Fiberglass_laminate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Germanium_dioxide",
    icon = "__NCP-Tech__/graphics/icons/Germanium_dioxide.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Oxide_glass",
    icon = "__NCP-Tech__/graphics/icons/Oxide_glass.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Glass_tube",
    icon = "__NCP-Tech__/graphics/icons/Glass_tube.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Purified_glass_tube",
    icon = "__NCP-Tech__/graphics/icons/Purified_glass_tube.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Optical_fiber",
    icon = "__NCP-Tech__/graphics/icons/Optical_fiber.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Germanium_concentrate",
    icon = "__NCP-Tech__/graphics/icons/Germanium_concentrate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Germanium",
    icon = "__NCP-Tech__/graphics/icons/Germanium.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  --Machiness
 
 
  {
    type= "item",
    name= "Rotary_kiln",
    icon = "__NCP-Tech__/graphics/icons/Rotary_kiln.png",
	flags = {"goes-to-quickbar"},
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Rotary_kiln",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Electric_furnace",
    icon = "__NCP-Tech__/graphics/icons/Electric_furnace.png",
	flags = {"goes-to-quickbar"},
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Electric_furnace",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Miningdrill_1",
    icon = "__base__/graphics/icons/basic-mining-drill.png",
	flags = {"goes-to-quickbar"},
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Miningdrill_1",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Crusher",
    icon = "__NCP-Tech__/graphics/icons/Crusher.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Crusher",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Ore_washing",
    icon = "__NCP-Tech__/graphics/icons/Ore_washing.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Ore_washing",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Chemical_plant",
    icon = "__NCP-Tech__/graphics/icons/Chemical_plant.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Chemical_plant",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Electrolyzer",
    icon = "__NCP-Tech__/graphics/icons/Electrolyzer.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Electrolyzer",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Chemical_furnace",
    icon = "__NCP-Tech__/graphics/icons/Chemical_furnace.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Chemical_furnace",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Pump",
    icon = "__NCP-Tech__/graphics/icons/Pump.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Pump",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Blast_furnace",
    icon = "__NCP-Tech__/graphics/icons/Blast_furnace.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Blast_furnace",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Nuclear_fuel_processing_plant",
    icon = "__NCP-Tech__/graphics/icons/Nuclear_fuel_processing_plant.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Nuclear_fuel_processing_plant",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Rolling_machine",
    icon = "__NCP-Tech__/graphics/icons/Rolling_machine.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Rolling_machine",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Mixer",
    icon = "__NCP-Tech__/graphics/icons/Mixer.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Mixer",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Cracking_plant",
    icon = "__NCP-Tech__/graphics/icons/Cracking_plant.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Cracking_plant",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Distillation",
    icon = "__NCP-Tech__/graphics/icons/Distillation.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Distillation",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Compressor",
    icon = "__NCP-Tech__/graphics/icons/Compressor.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Compressor",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Electric_arc_furnace",
    icon = "__NCP-Tech__/graphics/icons/Electric_arc_furnace.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Electric_arc_furnace",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Vacuum_oxygen_decarburization",
    icon = "__NCP-Tech__/graphics/icons/Vacuum_oxygen_decarburization.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Vacuum_oxygen_decarburization",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Grinding_mill",
    icon = "__NCP-Tech__/graphics/icons/Grinding_mill.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Grinding_mill",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Cryogenic_distillation_plant",
    icon = "__NCP-Tech__/graphics/icons/Cryogenic_distillation_plant.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Cryogenic_distillation_plant",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Farm",
    icon = "__NCP-Tech__/graphics/icons/Farm.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Farm",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Electronics_assembly_machine",
    icon = "__NCP-Tech__/graphics/icons/Electronics_assembly_machine.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Electronics_assembly_machine",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Flash_furnace",
    icon = "__NCP-Tech__/graphics/icons/Flash_furnace.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Flash_furnace",
    stack_size= 50,
  },
  {
    type= "item",
    name= "TSL_furnace",
    icon = "__NCP-Tech__/graphics/icons/TSL_furnace.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "TSL_furnace",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Extruder",
    icon = "__NCP-Tech__/graphics/icons/Extruder.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Extruder",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Milling_machine",
    icon = "__NCP-Tech__/graphics/icons/Milling_machine.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Milling_machine",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Furnace",
    icon = "__NCP-Tech__/graphics/icons/Furnace.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Furnace",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Assembling_machine",
    icon = "__NCP-Tech__/graphics/icons/Assembling_machine.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Assembling_machine",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Refinery",
    icon = "__NCP-Tech__/graphics/icons/Refinery.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Refinery",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Electric_flash_furnace",
    icon = "__NCP-Tech__/graphics/icons/Electric_flash_furnace.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Electric_flash_furnace",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lead_scrap",
    icon = "__NCP-Tech__/graphics/icons/Lead_scrap.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lead_dust",
    icon = "__NCP-Tech__/graphics/icons/Lead_dust.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lead_oxide",
    icon = "__NCP-Tech__/graphics/icons/Lead_oxide.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Magnesium_chloride",
    icon = "__NCP-Tech__/graphics/icons/Magnesium_chloride.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Wood_seed",
    icon = "__NCP-Tech__/graphics/icons/Wood_seed.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Cotton_seed",
    icon = "__NCP-Tech__/graphics/icons/Cotton_seed.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  
  
  
  
  
  
  
  
  
  
  
  
  
  --------------------------------------------
  {
    type= "item",
    name= "Wood_raw",
    icon = "__NCP-Tech__/graphics/icons/Wood_raw.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Uraninite_crushed_ore",
    icon = "__NCP-Tech__/graphics/icons/Uraninite_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Crushed",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Nickel_billet",
    icon = "__NCP-Tech__/graphics/icons/Nickel_billet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Sphalerite_crushed_ore",
    icon = "__NCP-Tech__/graphics/icons/Sphalerite_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Crushed",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Zinc_billet",
    icon = "__NCP-Tech__/graphics/icons/Zinc_billet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Rare_earth",
    icon = "__NCP-Tech__/graphics/icons/Rare_earth.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Coal_crushed_ore",
    icon = "__NCP-Tech__/graphics/icons/Coal_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Coal_dust",
    icon = "__NCP-Tech__/graphics/icons/Coal_dust.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
	fuel_value="300MJ"
  },
  {
    type= "item",
    name= "Coal_ore_dust",
    icon = "__NCP-Tech__/graphics/icons/Coal_ore_dust.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Rutile_ore_sand",
    icon = "__NCP-Tech__/graphics/icons/Rutile_ore_sand.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Rutile_sand",
    icon = "__NCP-Tech__/graphics/icons/Rutile_sand.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Electric_chemical_furnace",
    icon = "__NCP-Tech__/graphics/icons/Electric_chemical_furnace.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
	place_result= "Electric_chemical_furnace",
  },
  {
    type= "item",
    name= "Titanium_dioxide_pellet",
    icon = "__NCP-Tech__/graphics/icons/Titanium_dioxide_pellet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Titanium_pellet",
    icon = "__NCP-Tech__/graphics/icons/Titanium_pellet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Titanium_dust_dirty",
    icon = "__NCP-Tech__/graphics/icons/Titanium_dust_dirty.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Titanium_dust",
    icon = "__NCP-Tech__/graphics/icons/Titanium_dust.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Zirconium_sponge",
    icon = "__NCP-Tech__/graphics/icons/Zirconium_sponge.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Zirconium_tetrachloride",
    icon = "__NCP-Tech__/graphics/icons/Zirconium_tetrachloride.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Uranium_tetrafluoride",
    icon = "__NCP-Tech__/graphics/icons/Uranium_tetrafluoride.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Uranium_dioxide",
    icon = "__NCP-Tech__/graphics/icons/Uranium_dioxide.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Coal",
    icon = "__NCP-Tech__/graphics/icons/Coal.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },

  
  --CHEATS
  

  
  
  {
    type= "item",
    name= "aaaaaaCheatFuel",
    icon = "__NCP-Tech__/graphics/icons/Zinc_billet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 500,
	fuel_value = "800MJ",
  },
  
  
  
  
  
  
  
  })
