data.raw["item"]["coal"].fuel_value =nil
data.raw["item"]["raw-wood"].fuel_value =nil

data:extend({

 {
    type= "item",
    name= "Alumina",
    icon = "__NCP-Tech__/graphics/item/Alumina.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Raw_ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Nichrome",
    icon = "__NCP-Tech__/graphics/item/Nichrome.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Raw_ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lithium_carbonate",
    icon = "__NCP-Tech__/graphics/item/Lithium_carbonate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Raw_ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Sodium_chlorate",
    icon = "__NCP-Tech__/graphics/item/Sodium_chlorate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Raw_ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Sodium_perchlorate",
    icon = "__NCP-Tech__/graphics/item/Sodium_perchlorate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Raw_ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Quarried_limestone",
    icon = "__NCP-Tech__/graphics/item/Quarried_limestone.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Raw_ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Carbon_fiber_fabric",
    icon = "__NCP-Tech__/graphics/item/Carbon_fiber_fabric.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Raw_ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Carbon_fiber_filament",
    icon = "__NCP-Tech__/graphics/item/Carbon_fiber_filament.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Raw_ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "DNT",
    icon = "__NCP-Tech__/graphics/item/DNT.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Raw_ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "PAN_filament",
    icon = "__NCP-Tech__/graphics/item/PAN_filament.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Raw_ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "TNT",
    icon = "__NCP-Tech__/graphics/item/TNT.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Raw_ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Limestone_crushed",
    icon = "__NCP-Tech__/graphics/item/Limestone_crushed.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Raw_ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Aluminium_billet",
    icon = "__NCP-Tech__/graphics/item/Aluminium_billet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Ammonium_Paratungstate",
    icon = "__NCP-Tech__/graphics/item/Ammonium_Paratungstate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Asphalt_concrete",
    icon = "__NCP-Tech__/graphics/item/Asphalt_concrete.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Battery",
    icon = "__NCP-Tech__/graphics/item/Battery.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Battery_casing",
    icon = "__NCP-Tech__/graphics/item/Battery_casing.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Bauxite_concentrate",
    icon = "__NCP-Tech__/graphics/item/Bauxite_concentrate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Bauxite_crushed_ore",
    icon = "__NCP-Tech__/graphics/item/Bauxite_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Crushed",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Bauxite_ore",
    icon = "__NCP-Tech__/graphics/item/Bauxite_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Bauxite_tailings",
    icon = "__NCP-Tech__/graphics/item/Bauxite_tailings.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Brass_billet",
    icon = "__NCP-Tech__/graphics/item/Brass_billet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Brass_plate",
    icon = "__NCP-Tech__/graphics/item/Brass_plate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Calcium_chloride",
    icon = "__NCP-Tech__/graphics/item/Calcium_chloride.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Calcium_fluoride",
    icon = "__NCP-Tech__/graphics/item/Calcium_fluoride.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Calcium_oxide",
    icon = "__NCP-Tech__/graphics/item/Calcium_oxide.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Calcium_sulfate",
    icon = "__NCP-Tech__/graphics/item/Calcium_sulfate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Canister",
    icon = "__NCP-Tech__/graphics/item/Canister.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Carbon_dust",
    icon = "__NCP-Tech__/graphics/item/Carbon_dust.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Cassiterite_crushed_ore",
    icon = "__NCP-Tech__/graphics/item/Cassiterite_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Crushed",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Cassiterite_ore",
    icon = "__NCP-Tech__/graphics/item/Cassiterite_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Chalcopyrite_crushed_ore",
    icon = "__NCP-Tech__/graphics/item/Chalcopyrite_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Crushed",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Chalcopyrite_ore",
    icon = "__NCP-Tech__/graphics/item/Chalcopyrite_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Charcoal",
    icon = "__NCP-Tech__/graphics/item/Charcoal.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Chloroauric_acid",
    icon = "__NCP-Tech__/graphics/item/Chloroauric_acid.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Chromite_concentrate",
    icon = "__NCP-Tech__/graphics/item/Chromite_concentrate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Chromite_crushed_ore",
    icon = "__NCP-Tech__/graphics/item/Chromite_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Crushed",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Chromite_ore",
    icon = "__NCP-Tech__/graphics/item/Chromite_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Clay_dry",
    icon = "__NCP-Tech__/graphics/item/Clay_dry.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Clay_wet",
    icon = "__NCP-Tech__/graphics/item/Clay_wet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Coal_coke",
    icon = "__NCP-Tech__/graphics/item/Coal_coke.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
	fuel_value="280MJ"
  },
  {
    type= "item",
    name= "Coal_tar",
    icon = "__NCP-Tech__/graphics/item/Coal_tar.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Cobalt_oxide",
    icon = "__NCP-Tech__/graphics/item/Cobalt_oxide.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Copper_anode",
    icon = "__NCP-Tech__/graphics/item/Copper_anode.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Copper_billet",
    icon = "__NCP-Tech__/graphics/item/Copper_billet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Copper_blister",
    icon = "__NCP-Tech__/graphics/item/Copper_blister.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Copper_concentrate",
    icon = "__NCP-Tech__/graphics/item/Copper_concentrate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Copper_native_ore",
    icon = "__NCP-Tech__/graphics/item/Copper_native_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Copper_plate",
    icon = "__NCP-Tech__/graphics/item/Copper_plate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Copper_rod",
    icon = "__NCP-Tech__/graphics/item/Copper_rod.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Cordite",
    icon = "__NCP-Tech__/graphics/item/Cordite.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Cotton",
    icon = "__NCP-Tech__/graphics/item/Cotton.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Diesel_canister",
    icon = "__NCP-Tech__/graphics/item/Diesel_canister.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Direct_reduced_iron",
    icon = "__NCP-Tech__/graphics/item/Direct_reduced_iron.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Dore_bar",
    icon = "__NCP-Tech__/graphics/item/Dore_bar.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Ferrochrome",
    icon = "__NCP-Tech__/graphics/item/Ferrochrome.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Fertilizer",
    icon = "__NCP-Tech__/graphics/item/Fertilizer.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Fluorite_crushed_ore",
    icon = "__NCP-Tech__/graphics/item/Fluorite_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Crushed",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Fluorite_ore",
    icon = "__NCP-Tech__/graphics/item/Fluorite_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Galena_crushed_ore",
    icon = "__NCP-Tech__/graphics/item/Galena_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Crushed",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Galena_ore",
    icon = "__NCP-Tech__/graphics/item/Galena_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Glass",
    icon = "__NCP-Tech__/graphics/item/Glass.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Gold_concentrate",
    icon = "__NCP-Tech__/graphics/item/Gold_concentrate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Gold_crushed_ore",
    icon = "__NCP-Tech__/graphics/item/Gold_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Crushed",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Gold_ingot",
    icon = "__NCP-Tech__/graphics/item/Gold_ingot.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Gold_ore",
    icon = "__NCP-Tech__/graphics/item/Gold_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Gravel",
    icon = "__NCP-Tech__/graphics/item/Gravel.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Guncotton",
    icon = "__NCP-Tech__/graphics/item/Guncotton.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Gunpowder",
    icon = "__NCP-Tech__/graphics/item/Gunpowder.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lead_billet",
    icon = "__NCP-Tech__/graphics/item/Lead_billet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lead_bullion",
    icon = "__NCP-Tech__/graphics/item/Lead_bullion.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lead_concentrate",
    icon = "__NCP-Tech__/graphics/item/Lead_concentrate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lead_plate",
    icon = "__NCP-Tech__/graphics/item/Lead_plate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Li-ion_battery",
    icon = "__NCP-Tech__/graphics/item/Li-ion_battery.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lithium",
    icon = "__NCP-Tech__/graphics/item/Lithium.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lithium_chloride",
    icon = "__NCP-Tech__/graphics/item/Lithium_chloride.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lithium_cobalt_oxide",
    icon = "__NCP-Tech__/graphics/item/Lithium_cobalt_oxide.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lithium_perchlorate",
    icon = "__NCP-Tech__/graphics/item/Lithium_perchlorate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lithium_tungstate",
    icon = "__NCP-Tech__/graphics/item/Lithium_tungstate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Magnetite_concentrate",
    icon = "__NCP-Tech__/graphics/item/Magnetite_concentrate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Magnetite_crushed_ore",
    icon = "__NCP-Tech__/graphics/item/Magnetite_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Crushed",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Magnetite_ore",
    icon = "__NCP-Tech__/graphics/item/Magnetite_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Nickel",
    icon = "__NCP-Tech__/graphics/item/Nickel.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Nickel_cathode",
    icon = "__NCP-Tech__/graphics/item/Nickel_cathode.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Nickel_concentrate",
    icon = "__NCP-Tech__/graphics/item/Nickel_concentrate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Nickel_dust",
    icon = "__NCP-Tech__/graphics/item/Nickel_dust.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Nickel_plate",
    icon = "__NCP-Tech__/graphics/item/Nickel_plate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Pentlandite_crushed_ore",
    icon = "__NCP-Tech__/graphics/item/Pentlandite_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Crushed",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Pentlandite_ore",
    icon = "__NCP-Tech__/graphics/item/Pentlandite_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Petroleum_jelly",
    icon = "__NCP-Tech__/graphics/item/Petroleum_jelly.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Pig_iron",
    icon = "__NCP-Tech__/graphics/item/Pig_iron.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Pig_iron_early",
    icon = "__NCP-Tech__/graphics/item/Pig_iron.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Plastic_pellets",
    icon = "__NCP-Tech__/graphics/item/Plastic_pellets.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Quarried_stone",
    icon = "__NCP-Tech__/graphics/item/Quarried_stone.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Quartz",
    icon = "__NCP-Tech__/graphics/item/Quartz.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Quartz_rock",
    icon = "__NCP-Tech__/graphics/item/Quartz_rock.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Quartz_crushed",
    icon = "__NCP-Tech__/graphics/item/Quartz_crushed.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Crushed",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Resin",
    icon = "__NCP-Tech__/graphics/item/Resin.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Rubber",
    icon = "__NCP-Tech__/graphics/item/Rubber.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Rutile_crushed_ore",
    icon = "__NCP-Tech__/graphics/item/Rutile_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Crushed",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Rutile_ore",
    icon = "__NCP-Tech__/graphics/item/Rutile_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Salt",
    icon = "__NCP-Tech__/graphics/item/Salt.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Potassium_nitrate",
    icon = "__NCP-Tech__/graphics/item/Potassium_nitrate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Sand",
    icon = "__NCP-Tech__/graphics/item/Sand.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Scheelite_crushed_ore",
    icon = "__NCP-Tech__/graphics/item/Scheelite_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Crushed",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Scheelite_ore",
    icon = "__NCP-Tech__/graphics/item/Scheelite_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Silicon_boule",
    icon = "__NCP-Tech__/graphics/item/Silicon_boule.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Silicon_carbide",
    icon = "__NCP-Tech__/graphics/item/Silicon_carbide.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Silicon_dioxide",
    icon = "__NCP-Tech__/graphics/item/Silicon_dioxide.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Silicon_wafer",
    icon = "__NCP-Tech__/graphics/item/Silicon_wafer.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Silt",
    icon = "__NCP-Tech__/graphics/item/Silt.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Silver_ingot",
    icon = "__NCP-Tech__/graphics/item/Silver_ingot.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Silver_nitrate",
    icon = "__NCP-Tech__/graphics/item/Silver_nitrate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Silver_oxide",
    icon = "__NCP-Tech__/graphics/item/Silver_oxide.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Silver-oxide_battery",
    icon = "__NCP-Tech__/graphics/item/Silver-oxide_battery.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Slag",
    icon = "__NCP-Tech__/graphics/item/Slag.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Slag_dust",
    icon = "__NCP-Tech__/graphics/item/Slag_dust.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Sodium_hydroxide",
    icon = "__NCP-Tech__/graphics/item/Sodium_hydroxide.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Sphalerite_ore",
    icon = "__NCP-Tech__/graphics/item/Sphalerite_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Stainless_steel_billet",
    icon = "__NCP-Tech__/graphics/item/Stainless_steel_billet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Steel_billet",
    icon = "__NCP-Tech__/graphics/item/Steel_billet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Stone_crushed",
    icon = "__NCP-Tech__/graphics/item/Stone_crushed.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Crushed",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Styrofoam",
    icon = "__NCP-Tech__/graphics/item/Styrofoam.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Sulfur",
    icon = "__NCP-Tech__/graphics/item/Sulfur.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Tin_billet",
    icon = "__NCP-Tech__/graphics/item/Tin_billet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Tin_concentrate",
    icon = "__NCP-Tech__/graphics/item/Tin_concentrate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Titanium_billet",
    icon = "__NCP-Tech__/graphics/item/Titanium_billet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Titanium_nitride_film",
    icon = "__NCP-Tech__/graphics/item/Titanium_nitride_film.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Titanium_dioxide",
    icon = "__NCP-Tech__/graphics/item/Titanium_dioxide.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Tungsten_carbide_billet",
    icon = "__NCP-Tech__/graphics/item/Tungsten_carbide_billet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Tungsten_oxide",
    icon = "__NCP-Tech__/graphics/item/Tungsten_oxide.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Tungsten_powder",
    icon = "__NCP-Tech__/graphics/item/Tungsten_powder.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Uraninite_ore_concentrate",
    icon = "__NCP-Tech__/graphics/item/Uraninite_ore_concentrate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Uraninite_ore",
    icon = "__NCP-Tech__/graphics/item/Uraninite_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Uranium_235_pellet",
    icon = "__NCP-Tech__/graphics/item/Uranium_235_pellet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Uranium_235_rod",
    icon = "__NCP-Tech__/graphics/item/Uranium_235_rod.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Uranium_235_rod_alt",
    icon = "__NCP-Tech__/graphics/item/Uranium_235_rod_alt.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Uranium_238_pellet",
    icon = "__NCP-Tech__/graphics/item/Uranium_238_pellet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Uranium_oxide_powder_235",
    icon = "__NCP-Tech__/graphics/item/Uranium_oxide_powder_235.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Uranium_oxide_powder_238",
    icon = "__NCP-Tech__/graphics/item/Uranium_oxide_powder_238.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Wood",
    icon = "__NCP-Tech__/graphics/item/Wood.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
	fuel_value="180MJ"
  },
  {
    type= "item",
    name= "Wooden_board",
    icon = "__NCP-Tech__/graphics/item/Wooden_board.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Wrought_iron_billet",
    icon = "__NCP-Tech__/graphics/item/Wrought_iron_billet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Iron_billet",
    icon = "__NCP-Tech__/graphics/item/Wrought_iron_billet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Yellowcake",
    icon = "__NCP-Tech__/graphics/item/Yellowcake.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Zinc_concentrate",
    icon = "__NCP-Tech__/graphics/item/Zinc_concentrate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Zinc_matte",
    icon = "__NCP-Tech__/graphics/item/Zinc_matte.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Zinc_plate",
    icon = "__NCP-Tech__/graphics/item/Zinc_plate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Zircon",
    icon = "__NCP-Tech__/graphics/item/Zircon.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Zirconium_dust",
    icon = "__NCP-Tech__/graphics/item/Zirconium_dust.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Zirconium_billet",
    icon = "__NCP-Tech__/graphics/item/Zirconium_billet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Zirconium_plate",
    icon = "__NCP-Tech__/graphics/item/Zirconium_plate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Zirconium_tube",
    icon = "__NCP-Tech__/graphics/item/Zirconium_tube.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  
  
  ----------------------------
  
  {
    type= "item",
    name= "Lead_solder_ingot",
    icon = "__NCP-Tech__/graphics/item/Lead_solder_ingot.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lead_solder",
    icon = "__NCP-Tech__/graphics/item/Lead_solder.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lead_free_solder_ingot",
    icon = "__NCP-Tech__/graphics/item/Lead_free_solder_ingot.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lead_free_solder",
    icon = "__NCP-Tech__/graphics/item/Lead_free_solder.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Solder_paste",
    icon = "__NCP-Tech__/graphics/item/Solder_paste.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Magnesium_hydroxide",
    icon = "__NCP-Tech__/graphics/item/Magnesium_hydroxide.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Magnesium_oxide",
    icon = "__NCP-Tech__/graphics/item/Magnesium_oxide.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Ferrosilicon",
    icon = "__NCP-Tech__/graphics/item/Ferrosilicon.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Magnesium_billet",
    icon = "__NCP-Tech__/graphics/item/Magnesium_billet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Graphite_ore",
    icon = "__NCP-Tech__/graphics/item/Graphite_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Graphite_crushed_ore",
    icon = "__NCP-Tech__/graphics/item/Graphite_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Graphite_crushed",
    icon = "__NCP-Tech__/graphics/item/Graphite_crushed.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Graphite_dust",
    icon = "__NCP-Tech__/graphics/item/Graphite_dust.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Graphite_electrode",
    icon = "__NCP-Tech__/graphics/item/Graphite_electrode.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Cement",
    icon = "__NCP-Tech__/graphics/item/Cement.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Graphite_crucible",
    icon = "__NCP-Tech__/graphics/item/Graphite_crucible.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Graphite_rod",
    icon = "__NCP-Tech__/graphics/item/Graphite_rod.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Silicon_furnace",
    icon = "__NCP-Tech__/graphics/item/Silicon_furnace.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Cement_bauxite",
    icon = "__NCP-Tech__/graphics/item/Cement_bauxite.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Cement_slag",
    icon = "__NCP-Tech__/graphics/item/Cement_slag.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Calcium_carbonate",
    icon = "__NCP-Tech__/graphics/item/Calcium_carbonate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Cement_clinker",
    icon = "__NCP-Tech__/graphics/item/Cement_clinker.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Concrete_block",
    icon = "__NCP-Tech__/graphics/item/Concrete_block.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Concrete_pipe",
    icon = "__NCP-Tech__/graphics/item/Concrete_pipe.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "pipe",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Concrete_underground_pipe",
    icon = "__NCP-Tech__/graphics/item/Concrete_underground_pipe.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "underground_pipe",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Concrete_wall",
    icon = "__NCP-Tech__/graphics/item/Concrete_wall.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Sodium_carbonate",
    icon = "__NCP-Tech__/graphics/item/Sodium_carbonate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Diamond_uncut",
    icon = "__NCP-Tech__/graphics/item/Diamond_uncut.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Aluminosilicate_glass",
    icon = "__NCP-Tech__/graphics/item/Aluminosilicate_glass.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Fiberglass_roving",
    icon = "__NCP-Tech__/graphics/item/Fiberglass_roving.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Fiberglass_cloth",
    icon = "__NCP-Tech__/graphics/item/Fiberglass_cloth.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Fiberglass_laminate",
    icon = "__NCP-Tech__/graphics/item/Fiberglass_laminate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Germanium_dioxide",
    icon = "__NCP-Tech__/graphics/item/Germanium_dioxide.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Oxide_glass",
    icon = "__NCP-Tech__/graphics/item/Oxide_glass.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Glass_tube",
    icon = "__NCP-Tech__/graphics/item/Glass_tube.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Purified_glass_tube",
    icon = "__NCP-Tech__/graphics/item/Purified_glass_tube.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Optical_fiber",
    icon = "__NCP-Tech__/graphics/item/Optical_fiber.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Germanium_concentrate",
    icon = "__NCP-Tech__/graphics/item/Germanium_concentrate.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Germanium",
    icon = "__NCP-Tech__/graphics/item/Germanium.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "tool",
    name= "Credit",
    icon = "__NCP-Tech__/graphics/item/Credit.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "aa",
    stack_size= 100,
	durability = 1,
  },
  {
    type= "tool",
    name= "Credit100",
    icon = "__NCP-Tech__/graphics/item/Credit100.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "ab",
    stack_size= 100,
	durability = 1,
  },
  {
    type= "tool",
    name= "Credit10k",
    icon = "__NCP-Tech__/graphics/item/Credit10k.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "ac",
    stack_size= 100,
	durability = 1,
  },
  {
    type= "tool",
    name= "Credit1M",
    icon = "__NCP-Tech__/graphics/item/Credit1M.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "ad",
    stack_size= 1000,
	durability = 1,
  },
  {
    type= "tool",
    name= "Credit1G",
    icon = "__NCP-Tech__/graphics/item/Credit1G.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "ae",
    stack_size= 50,
	durability = 1,
  },
  {
    type= "item",
    name= "Silicon_metallurgical",
    icon = "__NCP-Tech__/graphics/item/Silicon_metallurgical.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Silicon_polycrystalline_granule",
    icon = "__NCP-Tech__/graphics/item/Silicon_polycrystalline_granule.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Silicon_polycrystalline_rod",
    icon = "__NCP-Tech__/graphics/item/Silicon_polycrystalline_rod.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "rod",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Bauxite_ore_dust",
    icon = "__NCP-Tech__/graphics/item/Silicon_polycrystalline_rod.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "rod",
    order= "a-b-c",
    stack_size= 50,
  },
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  --Machiness
 
 
  {
    type= "item",
    name= "Rotary_kiln",
    icon = "__NCP-Tech__/graphics/item/Rotary_kiln.png",
	flags = {"goes-to-quickbar"},
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Rotary_kiln",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Bank",
    icon = "__NCP-Tech__/graphics/item/Bank.png",
	flags = {"goes-to-quickbar"},
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Bank",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Market",
    icon = "__NCP-Tech__/graphics/item/Market.png",
	flags = {"goes-to-quickbar"},
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Market",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Filter",
    icon = "__NCP-Tech__/graphics/item/Filter.png",
	flags = {"goes-to-quickbar"},
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Filter",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Electric_furnace",
    icon = "__NCP-Tech__/graphics/item/Electric_furnace.png",
	flags = {"goes-to-quickbar"},
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Electric_furnace",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Miningdrill_1",
    icon = "__base__/graphics/icons/electric-mining-drill.png",
	flags = {"goes-to-quickbar"},
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Miningdrill_1",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Crusher",
    icon = "__NCP-Tech__/graphics/item/Crusher.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Crusher",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Ore_washing",
    icon = "__NCP-Tech__/graphics/item/Ore_washing.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Ore_washing",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Chemical_plant",
    icon = "__NCP-Tech__/graphics/item/Chemical_plant.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Chemical_plant",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Electrolyzer",
    icon = "__NCP-Tech__/graphics/item/Electrolyzer.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Electrolyzer",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Chemical_furnace",
    icon = "__NCP-Tech__/graphics/item/Chemical_furnace.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Chemical_furnace",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Pump",
    icon = "__NCP-Tech__/graphics/item/Pump.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Pump",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Blast_furnace",
    icon = "__NCP-Tech__/graphics/item/Blast_furnace.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Blast_furnace",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Nuclear_fuel_processing_plant",
    icon = "__NCP-Tech__/graphics/item/Nuclear_fuel_processing_plant.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Nuclear_fuel_processing_plant",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Rolling_machine",
    icon = "__NCP-Tech__/graphics/item/Rolling_machine.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Rolling_machine",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Mixer",
    icon = "__NCP-Tech__/graphics/item/Mixer.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Mixer",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Cracking_plant",
    icon = "__NCP-Tech__/graphics/item/Cracking_plant.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Cracking_plant",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Distillation",
    icon = "__NCP-Tech__/graphics/item/Distillation.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Distillation",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Compressor",
    icon = "__NCP-Tech__/graphics/item/Compressor.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Compressor",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Electric_arc_furnace",
    icon = "__NCP-Tech__/graphics/item/Electric_arc_furnace.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Electric_arc_furnace",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Vacuum_oxygen_decarburization",
    icon = "__NCP-Tech__/graphics/item/Vacuum_oxygen_decarburization.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Vacuum_oxygen_decarburization",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Grinding_mill",
    icon = "__NCP-Tech__/graphics/item/Grinding_mill.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Grinding_mill",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Cryogenic_distillation_plant",
    icon = "__NCP-Tech__/graphics/item/Cryogenic_distillation_plant.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Cryogenic_distillation_plant",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Farm",
    icon = "__NCP-Tech__/graphics/item/Farm.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Farm",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Electronics_assembly_machine",
    icon = "__NCP-Tech__/graphics/item/Electronics_assembly_machine.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Electronics_assembly_machine",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Flash_furnace",
    icon = "__NCP-Tech__/graphics/item/Flash_furnace.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Flash_furnace",
    stack_size= 50,
  },
  {
    type= "item",
    name= "TSL_furnace",
    icon = "__NCP-Tech__/graphics/item/TSL_furnace.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "TSL_furnace",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Extruder",
    icon = "__NCP-Tech__/graphics/item/Extruder.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Extruder",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Milling_machine",
    icon = "__NCP-Tech__/graphics/item/Milling_machine.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Milling_machine",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Furnace",
    icon = "__NCP-Tech__/graphics/item/Furnace.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Furnace",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Assembling_machine",
    icon = "__NCP-Tech__/graphics/item/Assembling_machine.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Assembling_machine",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Refinery",
    icon = "__NCP-Tech__/graphics/item/Refinery.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Refinery",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Electric_flash_furnace",
    icon = "__NCP-Tech__/graphics/item/Electric_flash_furnace.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Machines",
    order= "a-b-c",
	place_result = "Electric_flash_furnace",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lead_scrap",
    icon = "__NCP-Tech__/graphics/item/Lead_scrap.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lead_dust",
    icon = "__NCP-Tech__/graphics/item/Lead_dust.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Lead_oxide",
    icon = "__NCP-Tech__/graphics/item/Lead_oxide.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Magnesium_chloride",
    icon = "__NCP-Tech__/graphics/item/Magnesium_chloride.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Wood_seed",
    icon = "__NCP-Tech__/graphics/item/Wood_seed.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Cotton_seed",
    icon = "__NCP-Tech__/graphics/item/Cotton_seed.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  
  
  
  
  
  
  
  
  
  
  
  
  
  --------------------------------------------
  {
    type= "item",
    name= "Wood_raw",
    icon = "__NCP-Tech__/graphics/item/Wood_raw.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Uraninite_crushed_ore",
    icon = "__NCP-Tech__/graphics/item/Uraninite_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Crushed",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Nickel_billet",
    icon = "__NCP-Tech__/graphics/item/Nickel_billet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Sphalerite_crushed_ore",
    icon = "__NCP-Tech__/graphics/item/Sphalerite_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "Crushed",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Zinc_billet",
    icon = "__NCP-Tech__/graphics/item/Zinc_billet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Rare_earth",
    icon = "__NCP-Tech__/graphics/item/Rare_earth.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Coal_crushed_ore",
    icon = "__NCP-Tech__/graphics/item/Coal_crushed_ore.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Coal_dust",
    icon = "__NCP-Tech__/graphics/item/Coal_dust.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
	fuel_value="300MJ"
  },
  {
    type= "item",
    name= "Coal_ore_dust",
    icon = "__NCP-Tech__/graphics/item/Coal_ore_dust.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Rutile_ore_sand",
    icon = "__NCP-Tech__/graphics/item/Rutile_ore_sand.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Rutile_sand",
    icon = "__NCP-Tech__/graphics/item/Rutile_sand.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Electric_chemical_furnace",
    icon = "__NCP-Tech__/graphics/item/Electric_chemical_furnace.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
	place_result= "Electric_chemical_furnace",
  },
  {
    type= "item",
    name= "Titanium_dioxide_pellet",
    icon = "__NCP-Tech__/graphics/item/Titanium_dioxide_pellet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Titanium_pellet",
    icon = "__NCP-Tech__/graphics/item/Titanium_pellet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Titanium_dust_dirty",
    icon = "__NCP-Tech__/graphics/item/Titanium_dust_dirty.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Titanium_dust",
    icon = "__NCP-Tech__/graphics/item/Titanium_dust.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Zirconium_sponge",
    icon = "__NCP-Tech__/graphics/item/Zirconium_sponge.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Zirconium_tetrachloride",
    icon = "__NCP-Tech__/graphics/item/Zirconium_tetrachloride.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Uranium_tetrafluoride",
    icon = "__NCP-Tech__/graphics/item/Uranium_tetrafluoride.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Uranium_dioxide",
    icon = "__NCP-Tech__/graphics/item/Uranium_dioxide.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },
  {
    type= "item",
    name= "Coal",
    icon = "__NCP-Tech__/graphics/item/Coal.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 50,
  },

  
  --CHEATS
  

  
  
  {
    type= "item",
    name= "aaaaaaCheatFuel",
    icon = "__NCP-Tech__/graphics/item/Zinc_billet.png",
    flags= { "goes-to-main-inventory" },
    subgroup = "ores",
    order= "a-b-c",
    stack_size= 500,
	fuel_value = "800MJ",
  },
  
  
  
  
  
  
  
  })
